from __future__ import annotations

from typing import Protocol

from .schemas import (
    CallContext,
    CallRecord,
    ConfirmedJobSpec,
    QuoteDraft,
    QuoteLineItem,
    QuoteLineItemInput,
    QuoteTerm,
    QuoteTermInput,
    StructuredCallOutcome,
    TranscriptEvent,
    TranscriptEventInput,
    VendorTarget,
)


class CallerInputGateway(Protocol):
    """Read-only boundary owned by intake/vendor targeting modules."""

    def get_confirmed_job_spec(self, version_id: str) -> ConfirmedJobSpec | None: ...

    def get_vendor_target(self, vendor_id: str) -> VendorTarget | None: ...


class CallerStore(Protocol):
    def create_call(self, call: CallRecord) -> None: ...
    def get_call(self, call_id: str) -> CallRecord | None: ...
    def update_call(self, call: CallRecord) -> None: ...
    def append_call_event(self, call_id: str, event_type: str, payload: dict) -> str: ...
    def list_dialogue_actions(self, call_id: str) -> list[str]: ...
    def append_transcript(
        self, call_id: str, event: TranscriptEventInput
    ) -> TranscriptEvent: ...
    def get_transcript_event(self, event_id: str) -> TranscriptEvent | None: ...
    def list_transcript(self, call_id: str) -> list[TranscriptEvent]: ...
    def create_quote_draft(self, call_id: str) -> QuoteDraft: ...
    def get_quote_draft(self, call_id: str) -> QuoteDraft: ...
    def add_line_item(
        self, call_id: str, item: QuoteLineItemInput
    ) -> QuoteLineItem: ...
    def add_term(self, call_id: str, term: QuoteTermInput) -> QuoteTerm: ...
    def finalize_quote(self, call_id: str) -> QuoteDraft: ...
    def save_outcome(self, outcome: StructuredCallOutcome) -> None: ...
    def get_outcome(self, call_id: str) -> StructuredCallOutcome | None: ...


class VoiceSessionAdapter(Protocol):
    async def create_session(self, call_context: CallContext) -> str: ...
    async def send_context(self, session_id: str, context: CallContext) -> None: ...
    async def end_session(self, session_id: str) -> None: ...
    async def get_recording_reference(self, session_id: str) -> str | None: ...


class CallContextProvider(Protocol):
    """Optional program-level context; never an owner of confirmed call facts."""

    def build_and_snapshot(self, call_id: str, version_id: str) -> dict: ...

    def get_snapshot(self, call_id: str) -> dict | None: ...
